#----------------------------------------------------------------------
#	Abstract Syntax for PEST Statecharts
#	------------------------------------
#
#	$Id: Makefile,v 1.1 1998-11-30 09:25:31 swtech00 Exp $
#
#	$Log: not supported by cvs2svn $
#----------------------------------------------------------------------
 
DIRS	= "Absyn Editor STM Check GUI Simu CodeGen TESC1 TESC2"

all:	
	(cd .. ; javadoc -version -author -d PestDocu $(DIRS) )