

** Abstract: Pest


The repository collects the /sources/ of the ``Pest'' project
(/Programming environment for Statecharts/) , in the
software programming lab course ``Programming in the Many'', winter 
semester 1998/1999, at the University Kiel.

For the *webpages of the course project*, see [[https://martinsteffen.github.io/teaching/softtech/ws9899/pitm-pest][here]]


** Structure

This is the root of the Pest-project from the winter semester 1998/1999.
The package contains the following files and subdirectories:

  

    - [[,/Readme.org]]:        this file
    - [[./src]]:               sources
    - [[./baselines]]:         checked out versions of the various baselines
    - [[./baselines/jars]]:    jar files of end-of-semester baseline (for demo)
    - [[./safer]]:             the safer case study
    - [[./misc/cvsconfigs]]:   some original cvs configuration files



The webpages, administrative information, and generated documentation is
not part of the repos.


** Historical notes

The repository has been resurrected by migrating from ~cvs~ via svn (using
~cvs2svn~) and from there to ~git~. Caveats concerning missing branches
apply. Also the /Snapshots/ or baselines (original svn revision tags) seem
not to be preserved as git labels in the final repository (see the
[[./Baselines]]-file).  Also, original /authors/ have not been preserved, as
the original development was done all via ``anonoymous'' logins
~swtech<xx>~ (with ~swtech00~ the login for the course
administrator/teacher, the others one login per group); in general, the
contributors were the different students in the course plus the course
teachers.

*** CVS modules and configurability 

The original project relied on a relatively elaborate CVS-setup, making use
of /cvs-modules/. The purpose of the modules was the following. Different
components of the system were programmed by more than one group. In the
working directories at the client side, only /one/ configuration was
intended, like a mix-and-mash of different ``features'' (checkout the tool
with editor 1 + graph-placement 2 ....). That was regulated via cvs modules.

In the process of migration from cvs to svn to git, it's unlikely that this
setup has been properly preserved, i.e., the configurability has been lost.
For reference, the cvs-configuration files have been uploaded


