/**
 * dumpHA
 *
 * This class is responsible for generating our hierarchical
 * automaton.
 *
 * @version $Id: dumpHA.java,v 1.3 1999-01-04 14:19:15 swtech25 Exp $
 * @author Marcel Kyas
 */
package codegen;

import absyn.*;
import java.io.*;

public class dumpHA
{
	private Statechart S;
	private String path;

	/**
	 * This will construct a dumb instance of dumpHA.  You will
	 * need to set the state chart seperately.
	 */
	public dumpHA()
	{
		S = null;
		path = null;
	}


	/**
	 * This will construct some instance of dumpHA and will initialize
	 * its state chart with bla.
	 */
	public dumpHA(Statechart bla)
	{
		path = null;
		setStatechart(bla);
	}


	/**
	 * This will construct some instance of dumpHA and will initialize
	 * its path name with bla.
	 */
	public dumpHA(String bla)
	{
		S = null;
		setPathname(bla);
	}


	/**
	 * This will construct some instance of dumpHA and will initialize
	 * its state chart with bla and the path name to fasel.
	 */
	public dumpHA(Statechart bla, String fasel)
	{
		setStatechart(bla);
		setPathname(fasel);
	}


	/**
	 * Set statechart to bla.
	 */
	public void setStatechart(Statechart bla)
	{
		try {
			S = (Statechart) bla.clone();
		}
		catch (CloneNotSupportedException e) {
			// currently nothing.
		}
	}


	/**
	 * Set path to bla.
	 */
	public void setPathname(String bla)
	{
		path = bla;
	}


	/**
	 * In this section we will generate a symbol table.
	 *
	 * @exception CodeGenException if a code generation error
	 *	was encountered.
	 * @exception IOException What shall we say?
	 */
	private void dumpSymbolTable(OutputStreamWriter f)
		throws CodeGenException, IOException
	{
		final String[] state_head = {
			"static final String[] statenames = {"
		};

		final String[] state_tail = {
			"}"
		};

		final String[] event_head = {
			"static final String[] eventnames = {"
		};

		final String[] event_tail = {
			"}"
		};

		final String[] cond_head = {
			"static final String condition_names = {"
		};

		final String[] cond_tail = {
			"}"
		};

		final String[] head = {
			"/**",
			" * This code was automatically generated by codegen",
			" */",
			"public class SymbolTable {"
		};

		final String[] tail = {
			"boolean[] pre_states = new boolean[statenames.length];",
			"boolean[] post_states = new boolean[statenames.length];",
			"boolean[] pre_events = new boolean[eventnames.length];",
			"boolean[] post_events = new boolean[eventnames.length];",
			"boolean[] pre_cond = new boolean[condition_names.length];",
			"boolean[] post_cond = new boolean[condition_names.length];",

			"}"
		};

		int i;

		/* do the magick */
		for(i = 0; i < head.length; ++i) {
			f.write(head[i]);
		}
		for(i = 0; i < head.length; ++i) {
			f.write(state_head[i]);
		}
		// dump states
		for(i = 0; i < head.length; ++i) {
			f.write(state_tail[i]);
		}
		for(i = 0; i < head.length; ++i) {
			f.write(event_head[i]);
		}
		// dump events
		for(i = 0; i < head.length; ++i) {
			f.write(event_tail[i]);
		}
		for(i = 0; i < head.length; ++i) {
			f.write(cond_head[i]);
		}
		// dump conditions
		for(i = 0; i < head.length; ++i) {
			f.write(cond_tail[i]);
		}
		for(i = 0; i < head.length; ++i) {
			f.write(tail[i]);
		}
	}

	/**
	 * In this section we will generate the new
	 * events.
	 *
	 * @exception CodeGenException
	 */
	private void dumpNewEvents() throws CodeGenException
	{

	}

	/**
	 * This method will dump the hierarchical automaton
	 *
	 * @exception CodeGenException
	 */
	void dump() throws CodeGenException
	{

	}
}
