/**
 * This class will dump the tables of the automaton.
 */
package codegen;

import absyn.*;
import java.io.*;
import java.util.*;

/**
 * This class will dump the tables of our code.  Internallz
 * we will work with numerical values.  This is faster and
 * more efficient.  But we want to provide the environment
 * an interface to the original textual representations of
 * states, events and conditions.
 *
 * @version $Id: dumpTables.java,v 1.5 1999-01-20 18:47:26 swtech25 Exp $
 * @author Marcel Kyas
 */
public class dumpTables
{
	/*
	 * These are the generic code fragments we are going to create.
	 */
	private final String[] state_head = {
		"static final String[] statenames = {"
	};

	private final String[] state_tail = {
		"};",
		""
	};

	private final String[] event_head = {
		"static final String[] eventnames = {"
	};

	private final String[] event_tail = {
		"};",
		""
	};

	private final String[] cond_head = {
		"static final String[] condition_names = {"
	};

	private final String[] cond_tail = {
		"};",
		""
	};

	private final String[] head = {
		"/**",
		" * This code was automatically generated by codegen",
		" */",
		"public class SymbolTable {"
	};

	private final String[] tail = {
		"boolean[] his_states = new boolean[statenames.length];",
		"boolean[] pre_states = new boolean[statenames.length];",
		"boolean[] post_states = new boolean[statenames.length];",
		"boolean[] pre_events = new boolean[eventnames.length];",
		"boolean[] post_events = new boolean[eventnames.length];",
		"boolean[] pre_cond = new boolean[condition_names.length];",
		"boolean[] post_cond = new boolean[condition_names.length];",
		"}",
		""
	};


	private final float loadFactor = (float) 0.7;

	/*
	 * The private members.
	 */
	private Statechart S;
	private int state_curr_key = 0;
	private int event_curr_key = 0;
	private int cond_curr_key = 0;
	Hashtable states_sym = new Hashtable(1024, loadFactor);
	Hashtable events_sym = new Hashtable(1024, loadFactor);
	Hashtable cond_sym   = new Hashtable(1024, loadFactor);
	Path[]   states;
	String[] events;
	String[] cond;

	/**
	 * This is the only constructor for this class.  Do not use any
	 * other automatically generated constructors.
	 */
	public dumpTables(Statechart s)
	{
		S = s;
	}


	/**
	 * This method returns a string from path seperated by
	 * ch.
	 */
	private static String generateName(Path path, String ch)
	{
		String symbol = new String(path.head);
		Path name = path.tail;
		while (name != null) {
			symbol += (ch + name.head);
			name = name.tail;
		}
		return symbol;
	}


	/**
	 * Creates symbol names PathList and hashes them in Table.
	 */
	private void generateStateTable()
	{
		PathList current;
		Integer key;

		current = S.cnames;
		while (current != null) {
			// put them into Hash table, but check first.
			if (!states_sym.containsKey(current.head)) {
				key = new Integer(state_curr_key);
				states_sym.put(current.head, key);
				state_curr_key++;
			}
			current = current.tail;
		}
	}


	/**
	 * Creates symbol names PathList and hashes them in Table.
	 */
	private void generateEventTable()
	{
		SEventList current = S.events;
		Integer key;

		System.out.println("generateEventTable");
		while (current != null) {
			// put them into Hash table, but check first.

			if (!events_sym.containsKey(current.head)) {
				key = new Integer(event_curr_key);
				System.out.println(key + ": " + current.head.name);
				events_sym.put(current.head, key);
				event_curr_key++;
			}
			current = current.tail;
		}
	}


	/**
	 * Creates symbol names PathList and hashes them in Table.
	 */
	private void generateCondTable()
	{
		BvarList current = S.bvars;
		Integer key;

		while (current != null) {
			if (!cond_sym.containsKey(current.head)) {
				key = new Integer(cond_curr_key);
				cond_sym.put(current.head, key);
				cond_curr_key++;
			}
			current = current.tail;
		}
	}


	/**
	 * Now compute the inverse of the state hash table
	 */
	private void generateStateArray()
	{
		Enumeration e;
		Path p;
		Integer i;

		states = new Path[states_sym.size()];
		e = states_sym.keys();
		while (e.hasMoreElements()) {
			p = (Path) e.nextElement();
			i = (Integer) states_sym.get(p);
			 System.out.println(p + ": " + i);
			states[i.intValue()] = p;
		}
	}


	/**
	 * Create event array.
	 */
	private void generateEventArray()
	{
		Enumeration e;
		SEvent p;
		Integer i;

		System.out.println("event array");
		events = new String[events_sym.size()];
		e = events_sym.keys();
		while (e.hasMoreElements()) {
			p = (SEvent) e.nextElement();
			i = (Integer) events_sym.get(p);
			System.out.println(p.name + ": " + i);
			events[i.intValue()] = p.name;
		}
	}


	/**
	 * Create condition array.
	 */
	private void generateCondArray()
	{
		Enumeration e;
		Bvar p;
		Integer i;

		cond = new String[cond_sym.size()];
		e = cond_sym.keys();
		while (e.hasMoreElements()) {
			p = (Bvar) e.nextElement();
			i = (Integer) cond_sym.get(p);
			System.out.println(p.var + ": " + i);
			cond[i.intValue()] = p.var;
		}
	}


	/**
	 * Dump the state symbol table.
	 * @exceptions IOException self-explanatory.
	 */
	private void dumpStateSymbolTable(OutputStreamWriter f)
		throws IOException
	{
		int i;

		// This is a bit nasty:
		f.write("/**\n");
		f.write(" * The numbers belonging to the textual represen" +
			"tations.\n");
		f.write(" */\n");
		for(i = 0; i < states.length; ++i) {
			f.write("public static final int " +
				generateSymState(states[i]) +
				" = " + i + ";\n");
		}
		f.write("\n");
	}


	/**
	 * Dump the state name table.
	 * @exceptions IOException self-explanatory.
	 */
	private void dumpStateNames(OutputStreamWriter f)
		throws IOException
	{
		int i;

		for(i = 0; i < state_head.length; ++i) {
			f.write(state_head[i] + "\n");
		}
		for(i = 0; i < states.length - 1; ++i) {
			f.write("\"" + generateTextState(states[i]) + "\",\n");
		}
		if (states.length > 0) {
			f.write("\"" +
				 generateTextState(states[states.length - 1]) +
				 "\"\n");
		}
		for(i = 0; i < state_tail.length; ++i) {
			f.write(state_tail[i] + "\n");
		}
	}


	/**
	 * Dump the event name table.
	 * @exceptions IOException self-explanatory.
	 */
	private void dumpEventNames(OutputStreamWriter f)
		throws IOException
	{
		int i;

		for(i = 0; i < event_head.length; ++i) {
			f.write(event_head[i] + "\n");
		}
		for(i = 0; i < events.length - 1; ++i) {
			f.write("\"" + events[i] + "\",\n");
		}
		if (events.length > 0) {
			f.write("\"" + events[events.length - 1] + "\"\n");
		}
		for(i = 0; i < event_tail.length; ++i) {
			f.write(event_tail[i] + "\n");
		}
	}


	/**
	 * Dump the condition name table.
	 * @exceptions IOException self-explanatory.
	 */
	private void dumpCondNames(OutputStreamWriter f)
		throws IOException
	{
		int i;

		for(i = 0; i < cond_head.length; ++i) {
			f.write(cond_head[i] + "\n");
		}
		for(i = 0; i < cond.length - 1; ++i) {
			f.write("\"" + cond[i] + "\",\n");
		}
		if (cond.length > 0) {
			f.write("\"" + cond[cond.length - 1] + "\"\n");
		}
		for(i = 0; i < cond_tail.length; ++i) {
			f.write(cond_tail[i] + "\n");
		}
	}


	/**
	 * Generate the textual state name as a String.
	 */
	public static String generateTextState(Path path)
	{
		return generateName(path, ".");
	}


	/**
	 * Generate the symbolic state name as a String.
	 */
	public static String generateSymState(Path path)
	{
		return generateName(path, "_");
	}


	/**
	 * In this section we will generate a symbol table.
	 *
	 * @exception IOException What shall we say?
	 */
	private void dumpSymbolTable(OutputStreamWriter f)
		throws IOException
	{
		int i;

		for(i = 0; i < head.length; ++i) {
			f.write(head[i] + "\n");
		}
		dumpStateSymbolTable(f);
		dumpStateNames(f);
		dumpEventNames(f);
		dumpCondNames(f);
		for(i = 0; i < tail.length; ++i) {
			f.write(tail[i] + "\n");
		}
	}


	/**
	 * This method will create the necessary tables in one
	 * run and write them to disc.
	 *
	 * @exception IOException What shall we say?
	 */
	public void dump (OutputStreamWriter f) throws IOException
	{
		generateStateTable();
		generateStateArray();
		generateEventTable();
		generateEventArray();
		generateCondTable();
		generateCondArray();
		dumpSymbolTable(f);
	}
}
