all:
	cd ..; javac Check/*.java; javadoc  -version -author -d Check/Docu Check/*.java

clean:
	cd ..; rm -f Check/*.class *~

localdocu:      ;
	cd ..; javadoc  -version -author -d Check/Docu Check/*.java
