/*
 * This code was automatically generated by codegen
 */

import java.io.*;

/**
 * This class maintains the lists of symbols and generates
 * traces.  It also contains the finalizeStep method.
 */
public class SymbolTable {
	/**
	 * The numbers belonging to the textual representations
	 * of states.
	 */
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_SOUND_SOUND_DUMMY = 0;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_SOUND = 1;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_MAIN_MAIN_DUMMY = 2;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_MAIN = 3;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_CHANNEL_CHANNEL_DUMMY = 4;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_CHANNEL = 5;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_INFO_INFO_DUMMY = 6;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL_INFO = 7;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL_REMOTE_CONTROL_REMOTE_CONTROL = 8;
	public static final int SYSTEM_SYSTEM_SYSTEM_REMOTE_CONTROL = 9;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_VIDEOTEXT = 10;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW_CHANNELS_CH1 = 11;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW_CHANNELS_CH2 = 12;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW_CHANNELS = 13;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW_SM_CONTROL_REST = 14;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW_SM_CONTROL_SM_CONTROL_SOUND = 15;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW_SM_CONTROL = 16;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY_SHOW = 17;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_DISPLAY = 18;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_WORKING_SOUND_SOUND_ON = 19;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_WORKING_SOUND_MUTE = 20;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING_WORKING_SOUND = 21;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_WORKING = 22;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV_STANDBY = 23;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV_TV_TV = 24;
	public static final int SYSTEM_SYSTEM_SYSTEM_TV = 25;
	public static final int SYSTEM_SYSTEM_SYSTEM = 26;
	public static final int SYSTEM = 27;

	static final String[] statenames = {
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.SOUND.SOUND_DUMMY",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.SOUND",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.MAIN.MAIN_DUMMY",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.MAIN",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.CHANNEL.CHANNEL_DUMMY",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.CHANNEL",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.INFO.INFO_DUMMY",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL.INFO",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL.REMOTE_CONTROL_REMOTE_CONTROL",
		"SYSTEM.SYSTEM_SYSTEM.REMOTE_CONTROL",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.VIDEOTEXT",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW.CHANNELS.CH1",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW.CHANNELS.CH2",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW.CHANNELS",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW.SM_CONTROL.REST",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW.SM_CONTROL.SM_CONTROL_SOUND",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW.SM_CONTROL",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY.SHOW",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.DISPLAY",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.WORKING_SOUND.SOUND_ON",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.WORKING_SOUND.MUTE",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING.WORKING_SOUND",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.WORKING",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV.STANDBY",
		"SYSTEM.SYSTEM_SYSTEM.TV.TV_TV",
		"SYSTEM.SYSTEM_SYSTEM.TV",
		"SYSTEM.SYSTEM_SYSTEM",
		"SYSTEM"
	};

	/**
	 * The numbers belonging to the textual representations
	 * of events.
	 */
	public static final int EVENT_$$stop$$ = 0;
	public static final int EVENT_TV_OFF = 1;
	public static final int EVENT_TV_ON = 2;
	public static final int EVENT_TXT = 3;
	public static final int EVENT_TWO = 4;
	public static final int EVENT_ONE = 5;
	public static final int EVENT_MUTE = 6;
	public static final int EVENT_SOUND = 7;

	static final String[] eventnames = {
		"$$stop$$",
		"TV_OFF",
		"TV_ON",
		"TXT",
		"TWO",
		"ONE",
		"MUTE",
		"SOUND"
	};

	/**
	 * The numbers belonging to the textual representations
	 * of boolean variables.
	 */

	static final String[] condition_names = {
	};

	boolean[] his_states = new boolean[statenames.length];
	boolean[] pre_states = new boolean[statenames.length];
	boolean[] post_states = new boolean[statenames.length];
	boolean[] pre_events = new boolean[eventnames.length];
	boolean[] post_events = new boolean[eventnames.length];
	boolean[] pre_cond = new boolean[condition_names.length];
	boolean[] post_cond = new boolean[condition_names.length];

	/**
	 * This method updates the different fields after
	 * the completion of a step of the automaton
	 */
	public void finalizeStep() {
		pre_cond = post_cond;
		post_cond = new boolean[condition_names.length];
		pre_events = post_events;
		post_events = new boolean[eventnames.length];
		his_states = pre_states;
		pre_states = post_states;
		post_states = new boolean[statenames.length];
	}
}
