#----------------------------------------------------------------------
#	Abstract Syntax for PEST Statecharts
#	------------------------------------
#
#	$Id: Makefile,v 1.3 1998-11-26 17:10:41 swtech00 Exp $
#
#	$Log: not supported by cvs2svn $
#	Revision 1.2  1998/11/26 16:32:19  swtech00
#	Id and Log extension
#
#
#----------------------------------------------------------------------


all:
	javac *.java

clean:
	\rm -f *.class *~

