#----------------------------------------------------------------------
#	Abstract Syntax for PEST Statecharts
#	------------------------------------
#
#	$Id: Makefile,v 1.2 1998-11-26 16:32:19 swtech00 Exp $
#
#	$Log: not supported by cvs2svn $
#
#----------------------------------------------------------------------


clean:
	\rm -f *.class *~

all:
	javac *.java